CREATE TABLE mytable(
   Field1 VARCHAR(28) NOT NULL PRIMARY KEY
);
INSERT INTO mytable(Field1) VALUES ('Animated movies');
INSERT INTO mytable(Field1) VALUES ('Application software');
INSERT INTO mytable(Field1) VALUES ('Audio mastering');
INSERT INTO mytable(Field1) VALUES ('Bars');
INSERT INTO mytable(Field1) VALUES ('Beauty');
INSERT INTO mytable(Field1) VALUES ('Black Friday (shopping)');
INSERT INTO mytable(Field1) VALUES ('Bollywood movies');
INSERT INTO mytable(Field1) VALUES ('Brand');
INSERT INTO mytable(Field1) VALUES ('Business');
INSERT INTO mytable(Field1) VALUES ('Buy More');
INSERT INTO mytable(Field1) VALUES ('Cake');
INSERT INTO mytable(Field1) VALUES ('Cake (band)');
INSERT INTO mytable(Field1) VALUES ('Canada');
INSERT INTO mytable(Field1) VALUES ('Carleton University');
INSERT INTO mytable(Field1) VALUES ('Click (2006 film)');
INSERT INTO mytable(Field1) VALUES ('Clothing');
INSERT INTO mytable(Field1) VALUES ('Cosmetics');
INSERT INTO mytable(Field1) VALUES ('Cyber Monday');
INSERT INTO mytable(Field1) VALUES ('Deal of the day');
INSERT INTO mytable(Field1) VALUES ('Dentist');
INSERT INTO mytable(Field1) VALUES ('Desserts');
INSERT INTO mytable(Field1) VALUES ('Dil');
INSERT INTO mytable(Field1) VALUES ('Discounts and allowances');
INSERT INTO mytable(Field1) VALUES ('Eating');
INSERT INTO mytable(Field1) VALUES ('Employment');
INSERT INTO mytable(Field1) VALUES ('Entertainment');
INSERT INTO mytable(Field1) VALUES ('Fashion (film)');
INSERT INTO mytable(Field1) VALUES ('Fashion accessories');
INSERT INTO mytable(Field1) VALUES ('Fondant icing');
INSERT INTO mytable(Field1) VALUES ('Food');
INSERT INTO mytable(Field1) VALUES ('Food Network');
INSERT INTO mytable(Field1) VALUES ('H&M');
INSERT INTO mytable(Field1) VALUES ('Hair products');
INSERT INTO mytable(Field1) VALUES ('Higher education');
INSERT INTO mytable(Field1) VALUES ('Icing (food)');
INSERT INTO mytable(Field1) VALUES ('IPhone');
INSERT INTO mytable(Field1) VALUES ('Jewelry');
INSERT INTO mytable(Field1) VALUES ('Job hunting');
INSERT INTO mytable(Field1) VALUES ('LinkedIn');
INSERT INTO mytable(Field1) VALUES ('Love');
INSERT INTO mytable(Field1) VALUES ('Luxury goods');
INSERT INTO mytable(Field1) VALUES ('Magazines');
INSERT INTO mytable(Field1) VALUES ('Meditation');
INSERT INTO mytable(Field1) VALUES ('Music');
INSERT INTO mytable(Field1) VALUES ('Music videos');
INSERT INTO mytable(Field1) VALUES ('Network (film)');
INSERT INTO mytable(Field1) VALUES ('Online');
INSERT INTO mytable(Field1) VALUES ('Online shopping');
INSERT INTO mytable(Field1) VALUES ('Ontario');
INSERT INTO mytable(Field1) VALUES ('Oshawa');
INSERT INTO mytable(Field1) VALUES ('Parties');
INSERT INTO mytable(Field1) VALUES ('Plato');
INSERT INTO mytable(Field1) VALUES ('popeyes canada');
INSERT INTO mytable(Field1) VALUES ('Product (business)');
INSERT INTO mytable(Field1) VALUES ('Recruitment');
INSERT INTO mytable(Field1) VALUES ('Retail');
INSERT INTO mytable(Field1) VALUES ('RÃ©sumÃ©');
INSERT INTO mytable(Field1) VALUES ('Sales');
INSERT INTO mytable(Field1) VALUES ('Sales promotion');
INSERT INTO mytable(Field1) VALUES ('Sandal');
INSERT INTO mytable(Field1) VALUES ('Shoes');
INSERT INTO mytable(Field1) VALUES ('Shopping');
INSERT INTO mytable(Field1) VALUES ('Shopping and fashion');
INSERT INTO mytable(Field1) VALUES ('Shopping malls');
INSERT INTO mytable(Field1) VALUES ('Slice (TV channel)');
INSERT INTO mytable(Field1) VALUES ('Social network');
INSERT INTO mytable(Field1) VALUES ('Sterilization (microbiology)');
INSERT INTO mytable(Field1) VALUES ('Stock');
INSERT INTO mytable(Field1) VALUES ('Student Life Network');
INSERT INTO mytable(Field1) VALUES ('Sunday');
INSERT INTO mytable(Field1) VALUES ('The Flash (2014 TV series)');
INSERT INTO mytable(Field1) VALUES ('The Social Network');
INSERT INTO mytable(Field1) VALUES ('Thursday');
INSERT INTO mytable(Field1) VALUES ('Trinidad and Tobago');
INSERT INTO mytable(Field1) VALUES ('Ubereats');
INSERT INTO mytable(Field1) VALUES ('University');
INSERT INTO mytable(Field1) VALUES ('Warehouse');
INSERT INTO mytable(Field1) VALUES ('YouTube');
